### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/modular-type-along#1]
If you ask me, one of the last things you could do is add a command line interface. (actually I'd probably add it earlier, but it fits as the last commit here)

To avoid stress of live-typing, here is roughly what I would do:

```
import argparse

parser = argparse.ArgumentParser(description='Compute average temperature.')
parser.add_argument('input-csv', help='input CSV file')
parser.add_argument('-n', type=int, default=25, help='number of lines to process')
parser.add_argument('output-plot', help='output PNG filename')
args = parser.parse_args()

...
temperatures = read_data(args.input_csv, args.n)
mean = get_statistics(temperatures)
create_plot(temperatures, mean, args.output_plot)

print('the mean was', mean, 'celsius')
```

Discussion: then, this code can be applied to anything, without editing the code itself.  Shell scripting helps you do this efficiently - snakemake, workflow systems.

**Comment by bast** [comment]
Thanks! Great idea and I hope that CLI will come up during discussion as an alternative to code duplication and we can discuss pros and cons of looping inside the code or "outside" (workflows). Too tired to add it to the material now but I will keep it here for reference.

**Comment by bast** [comment]
I will add this. Indeed CLIs help me to keep the code itself more state-less.

**Comment by bast** [comment]
I added this point to the instructor guide. Great suggestion.
