### ISSUE TITLE
mention the thought of "global data structures" vs "local data structures"

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/modular-type-along#6]
A user when talking about modular code development, mentioned how new scientists had trouble separating what needs to be global vs what needs to be local.  This is already mentioned here along with the "global state" stuff, but I really liked the way this was mentioned in this conversation, to make it more explicit.

I'm not sure how to use this suggestion or if it can be, though.

credit/source @milicasan

**Comment by bast** [comment]
Great thought! At least wrote this as bullet point to not forget: 7e2e503cd80d36c5fc0f190622ff4b5484690605
